### ISSUE TITLE
Retrieve the background color

### ISSUE THREAD

**Issue by lucasmotta** [rafaeldias/swf-reader#2]
I've been trying to do that for the past 2 days, but with no success. I've been using this as a reference:
http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/swf/pdf/swf-file-format-spec.pdf

And I've also found this good library from Sephiroth:
http://www.sephiroth.it/swfreader.php

Do you have any ideas of how to achieve this?

**Comment by rafaeldias** [comment]
SWF format is made of tags. Each tag contains a header and its contents, as described in the link you are using as reference. Reading those properties of the tag is part of the tasks that I'm working on and will be available soon.

Anyway, to solve your problem for now, you can replace the code starting at the line `99` of the `index.js` : 
```javascript
/*switch( tagHeader.code ) {
  case SWFTags.FileAttributes : 
    break;
  default:
    buff.pointer += tag.length;
    break;
}*/
```
With :
```javascript
switch( tagHeader.code ) {
  case SWFTags.SetBackgroundColor : 
    swf.backgroundColor = tag.backgroundColor = [buff.readUInt8(), buff.readUInt8(), buff.readUInt8()];
    break;
  default:
    buff.pointer += tagHeader.length;
    break;
 }
// buff.pointer += tagHeader.length;
tags.push(tag); 
```

`SWFTags.SetBackgroundColor` is the ID of the tag that contains the `RGB` of the background color.
As described in the SWF spec : 
> The RGB record represents a color as a 24-bit red, green, and blue value.

Each RGB value is represented as unsigned 8-bit integer value (`UI8`), so using ` [buff.readUInt8(), buff.readUInt8(), buff.readUInt8()]` will retrieve each of those values.

Now you can access the RGB of the background color in your code like this : `swf.backgroundColor`.

You can even retrieve the hexadecimal value of the color by calculating its values : 
```javascript
var SWFReader = require('swf-reader');

SWFReader.read( 'swf_path.swf', function(err, swf) {
  if ( err ) {
    // handle error
  }
  var red = swf.backgroundColor[0]
     , green = swf.backgroundColor[1]
     , blue = swf.backgroundColor[2];

  console.log('Background Color (Hex): ' + (red*65546 + green*256 + blue).toString(16));
});
```

Hope it helps.

**Comment by lucasmotta** [comment]
Awesome, thanks for your help @rafaeldias, it worked like a charm!! I've created a temporary fork for now :)
